export const livros = {
  "011": {
    nome: "Fórmula 1 - O Grande Desafio",
    gabarito: [
      { id: 1, respostaCorreta: "C" },
      { id: 2, respostaCorreta: "B" },
      { id: 3, respostaCorreta: "A" },
      { id: 4, respostaCorreta: "A" },
      { id: 5, respostaCorreta: "D" },
      { id: 6, respostaCorreta: "C" },
      { id: 7, respostaCorreta: "B" },
      { id: 8, respostaCorreta: "D" },
      { id: 9, respostaCorreta: "A" },
      { id: 10, respostaCorreta: "A" },
      { id: 11, respostaCorreta: "D" },
      { id: 12, respostaCorreta: "B" },
      { id: 13, respostaCorreta: "B" },
      { id: 14, respostaCorreta: "B" },
      { id: 15, respostaCorreta: "C" },
      { id: 16, respostaCorreta: "B" },
      { id: 17, respostaCorreta: "D" },
      { id: 18, respostaCorreta: "D" },
      { id: 19, respostaCorreta: "D" },
      { id: 20, respostaCorreta: "B" },
      { id: 21, respostaCorreta: "D" },
      { id: 22, respostaCorreta: "A" },
      { id: 23, respostaCorreta: "B" },
      { id: 24, respostaCorreta: "B" },
      { id: 25, respostaCorreta: "B" },
      { id: 26, respostaCorreta: "D" },
      { id: 27, respostaCorreta: "A" },
      { id: 28, respostaCorreta: "B" },
      { id: 29, respostaCorreta: "A" },
      { id: 30, respostaCorreta: "B" }
    ],
  },
  "012": {
    nome: "Fórmula 1 - O Grande Desafio",
    gabarito: [  
      { id: 31, respostaCorreta: "C" },
      { id: 32, respostaCorreta: "B" },
      { id: 33, respostaCorreta: "D" },
      { id: 34, respostaCorreta: "A" },
      { id: 35, respostaCorreta: "C" },
      { id: 36, respostaCorreta: "A" },
      { id: 37, respostaCorreta: "B" },
      { id: 38, respostaCorreta: "B" },
      { id: 39, respostaCorreta: "A" },
      { id: 40, respostaCorreta: "C" },
      { id: 41, respostaCorreta: "B" },
      { id: 42, respostaCorreta: "C" },
      { id: 43, respostaCorreta: "C" },
      { id: 44, respostaCorreta: "C" },
      { id: 45, respostaCorreta: "D" },
      { id: 46, respostaCorreta: "C" },
      { id: 47, respostaCorreta: "B" },
      { id: 48, respostaCorreta: "C" },
      { id: 49, respostaCorreta: "D" },
      { id: 50, respostaCorreta: "B" },
      { id: 51, respostaCorreta: "D" },
      { id: 52, respostaCorreta: "D" },
      { id: 53, respostaCorreta: "D" },
      { id: 54, respostaCorreta: "D" },
      { id: 55, respostaCorreta: "C" },
      { id: 56, respostaCorreta: "A" },
      { id: 57, respostaCorreta: "A" },
      { id: 58, respostaCorreta: "C" },
      { id: 59, respostaCorreta: "C" },
      { id: 60, respostaCorreta: "B" }
    ],
  },
    "013": {
    nome: "Fórmula 1 - O Grande Desafio",
    gabarito: [  
      { id: 61, respostaCorreta: "B" },
      { id: 62, respostaCorreta: "D" },
      { id: 63, respostaCorreta: "A" },
      { id: 64, respostaCorreta: "C" },
      { id: 65, respostaCorreta: "A" },
      { id: 66, respostaCorreta: "C" },
      { id: 67, respostaCorreta: "C" },
      { id: 68, respostaCorreta: "B" },
      { id: 69, respostaCorreta: "D" },
      { id: 70, respostaCorreta: "D" },
      { id: 71, respostaCorreta: "D" },
      { id: 72, respostaCorreta: "D" },
      { id: 73, respostaCorreta: "D" },
      { id: 74, respostaCorreta: "A" },
      { id: 75, respostaCorreta: "C" },
      { id: 76, respostaCorreta: "C" },
      { id: 77, respostaCorreta: "B" },
      { id: 78, respostaCorreta: "A" },
      { id: 79, respostaCorreta: "D" },
      { id: 80, respostaCorreta: "B" },
      { id: 81, respostaCorreta: "C" },
      { id: 82, respostaCorreta: "B" },
      { id: 83, respostaCorreta: "B" },
      { id: 84, respostaCorreta: "C" },
      { id: 85, respostaCorreta: "C" },
      { id: 86, respostaCorreta: "D" },
      { id: 87, respostaCorreta: "D" },
      { id: 88, respostaCorreta: "B" },
      { id: 89, respostaCorreta: "B" },
      { id: 90, respostaCorreta: "A" }
    ],
  },
  "014": {
    nome: "Fórmula 1 - O Grande Desafio",
    gabarito: [  
      { id: 91, respostaCorreta: "D" },
      { id: 92, respostaCorreta: "C" },
      { id: 93, respostaCorreta: "A" },
      { id: 94, respostaCorreta: "C" },
      { id: 95, respostaCorreta: "D" },
      { id: 96, respostaCorreta: "C" },
      { id: 97, respostaCorreta: "D" },
      { id: 98, respostaCorreta: "C" },
      { id: 99, respostaCorreta: "C" },
      { id: 100, respostaCorreta: "B" },
      { id: 101, respostaCorreta: "B" },
      { id: 102, respostaCorreta: "A" },
      { id: 103, respostaCorreta: "D" },
      { id: 104, respostaCorreta: "B" },
      { id: 105, respostaCorreta: "A" },
      { id: 106, respostaCorreta: "B" },
      { id: 107, respostaCorreta: "B" },
      { id: 108, respostaCorreta: "D" },
      { id: 109, respostaCorreta: "A" },
      { id: 110, respostaCorreta: "B" },
      { id: 111, respostaCorreta: "B" },
      { id: 112, respostaCorreta: "C" },
      { id: 113, respostaCorreta: "C" },
      { id: 114, respostaCorreta: "D" },
      { id: 115, respostaCorreta: "A" },
      { id: 116, respostaCorreta: "B" },
      { id: 117, respostaCorreta: "B" },
      { id: 118, respostaCorreta: "C" },
      { id: 119, respostaCorreta: "B" },
      { id: 120, respostaCorreta: "D" }
    ],
  },
  "015": {
    nome: "Fórmula 1 - O Grande Desafio",
    gabarito: [  
      { id: 121, respostaCorreta: "A" },
      { id: 122, respostaCorreta: "C" },
      { id: 123, respostaCorreta: "C" },
      { id: 124, respostaCorreta: "D" },
      { id: 125, respostaCorreta: "D" },
      { id: 126, respostaCorreta: "A" },
      { id: 127, respostaCorreta: "A" },
      { id: 128, respostaCorreta: "B" },
      { id: 129, respostaCorreta: "D" },
      { id: 130, respostaCorreta: "C" },
      { id: 131, respostaCorreta: "C" },
      { id: 132, respostaCorreta: "D" },
      { id: 133, respostaCorreta: "D" },
      { id: 134, respostaCorreta: "C" },
      { id: 135, respostaCorreta: "C" },
      { id: 136, respostaCorreta: "B" },
      { id: 137, respostaCorreta: "D" },
      { id: 138, respostaCorreta: "B" },
      { id: 139, respostaCorreta: "B" },
      { id: 140, respostaCorreta: "C" },
      { id: 141, respostaCorreta: "B" },
      { id: 142, respostaCorreta: "D" },
      { id: 143, respostaCorreta: "A" },
      { id: 144, respostaCorreta: "B" },
      { id: 145, respostaCorreta: "D" },
      { id: 146, respostaCorreta: "D" },
      { id: 147, respostaCorreta: "D" },
      { id: 148, respostaCorreta: "B" },
      { id: 149, respostaCorreta: "C" },
      { id: 150, respostaCorreta: "C" }
    ]
  }
}